### ISSUE TITLE
Downloading the Bodhidharma and SAC datasets

### ISSUE THREAD

**Issue by adrienchaton** [DDMAL/jMIR#2]
Hello,

I would like to download the Bodhidharma and SAC MIDI datasets for research purpose.

I could not find where to access them. Are they available for download please ?

Best regards.

**Comment by codaich** [comment]
Hi Adrien

You can (temporarily) access the Bodhidharma MIDI files here:

https://drive.google.com/file/d/1usCFxiSXU05fBP9ePFd8J0oRJ4prKmth/view?usp=sharing

and the SLAC MIDI files here:

https://drive.google.com/file/d/15pN_scqNgbEairhm5X4im5sqz0-vLmip/view?usp=sharing

All the best,
Cory

**Comment by adrienchaton** [comment]
Thank you Cory !
